language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

before_install:
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

install: 
  # Wt
  #- sudo apt-get install witty witty-dbg witty-dev witty-doc
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download depencenies
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Build and run console version
  - qmake -qt=qt5 ToolHometrainerConsole.pro
  - make --silent debug
  - ./ToolHometrainerConsole --example
  - ./ToolHometrainerConsole --filename ToolHometrainerExerciseTest.txt &
  - sleep 1
  # - sudo killall -9 ToolHometrainerConsole #No need to kill it?
  # Build and run desktop version
  - qmake -qt=qt5 ToolHometrainerDesktop.pro
  - make --silent debug
  - ./ToolHometrainerDesktop &
  - sudo killall -9 ToolHometrainerDesktop
  # Build and run website version
  #- qmake -qt=qt5 ToolHometrainerWebsite.pro
  #- make --silent debug
  #- ./ToolHometrainerWebsite &
  #- sudo killall -9 ToolHometrainerWebsite
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)