language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

addons: 
  apt: 
    packages: 
      - libboost-all-dev

before_install:
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

install: 
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download depencenies
  - ./download_other_githubs

services:
 - xvfb

script: 
  # Build and run console version
  - qmake -qt=qt5 ToolHometrainerConsole.pro
  - make --silent debug
  - ./ToolHometrainerConsole --example
  - ./ToolHometrainerConsole --filename ToolHometrainerExerciseTest.txt &
  - sleep 1
  # - sudo killall -9 ToolHometrainerConsole #No need to kill it?
  # Build and run desktop version
  - qmake -qt=qt5 ToolHometrainerDesktop.pro
  - make --silent debug
  - ./ToolHometrainerDesktop &
  - sudo killall -9 ToolHometrainerDesktop
  # Build and run website version
  - qmake -qt=qt5 ToolHometrainerWebsite.pro
  - make --silent debug
  - ./ToolHometrainerWebsite &
  - sudo killall -9 ToolHometrainerWebsite
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)